name: build

on: workflow_dispatch

env:
    MAKEFLAGS: -j2
    EMSCRIPTEN_VERSION: 2.0.24

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: ${{env.EMSCRIPTEN_VERSION}}
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Build wasm busyide
        run: make $MAKEFLAGS dist
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hub release create -m "Build assets" -a dist/busybox_unstripped.js -a dist/busybox_unstripped.wasm build_${{github.sha}}
